baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = '医学影像检查项目名称及编码标准'
theme = 'ananke'

# 默认语言设置
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

# 语言设置
[languages]
  [languages.zh]
    languageCode = "zh-CN"
    languageName = "简体中文"
    title = "医学影像标准"
    weight = 1
    [languages.zh.params]
      description = "医学影像检查项目名称及编码标准官方网站"
      featured_image = "/images/banner.jpg"

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "Medical Imaging Standards"
    weight = 2
    [languages.en.params]
      description = "Official website for Medical Imaging Examination Project Names and Coding Standards"
      featured_image = "/images/banner.jpg"

[params]
  description = "医学影像检查项目名称及编码标准官方网站"
  featured_image = "/images/banner.jpg"
  mainSections = ["news", "blog"]
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "标准介绍"
    url = "/standards/"
    weight = 2
  [[menu.main]]
    name = "数据看板"
    url = "/dashboard/"
    weight = 3
  [[menu.main]]
    name = "标准查询"
    url = "/search/"
    weight = 4
  [[menu.main]]
    name = "新闻和博客"
    url = "/news/"
    weight = 5
  [[menu.main]]
    name = "AI大模型"
    url = "/ai-playground/"
    weight = 6
  [[menu.main]]
    name = "关于我们"
    url = "/about/"
    weight = 7

[languages.en.menu]
  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[languages.en.menu.main]]
    name = "Standards"
    url = "/standards/"
    weight = 2
  [[languages.en.menu.main]]
    name = "Dashboard"
    url = "/dashboard/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4
  [[languages.en.menu.main]]
    name = "News & Blog"
    url = "/news/"
    weight = 5
  [[languages.en.menu.main]]
    name = "AI Model"
    url = "/ai-playground/"
    weight = 6
  [[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 7

[params.footer]
  copyright = " 2024 . All rights reserved."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
