baseURL = 'http://localhost:1313/'
languageCode = 'zh-cn'
title = 'Imaging Standard Website'
theme = 'ananke'

[params]
  author = "Charlie"
  site_logo = ""
  description = "Welcome to Imaging Standard Website"
  background_color_class = "bg-black"
  recent_posts_number = 5
  featured_image = "images/about-featured.jpg"  # 移除开头的斜杠
  
  # 社交媒体链接
  [[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/youraccount"
  
  [[params.ananke_socials]]
  name = "github"
  url = "https://github.com/youraccount"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3