backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1

local_backend: true

media_folder: "static/images"
public_folder: "/images"

locale: 'zh_Hans'

editor:
  preview: true
  frame: true

collections:
  - name: "zh_posts"
    label: "文章"
    folder: "content/zh/posts"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "特色图片", name: "featured_image", widget: "image", required: false}
      - {label: "描述", name: "description", widget: "text"}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "zh_standards"
    label: "标准介绍"
    folder: "content/zh/standards"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "排序", name: "weight", widget: "number", default: 100, value_type: "int"}
      - {label: "描述", name: "description", widget: "text"}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "pages"
    label: "页面"
    files:
      - file: "content/zh/_index.md"
        label: "中文首页"
        name: "zh_home"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "描述", name: "description", widget: "text"}
          - {label: "内容", name: "body", widget: "markdown"}
      
      - file: "content/zh/about.md"
        label: "关于页面"
        name: "zh_about"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "描述", name: "description", widget: "text"}
          - {label: "内容", name: "body", widget: "markdown"}

site_url: http://localhost:1313
