backend:
  name: git
  branch: feature/add-netlify-cms

media_folder: "static/images"
public_folder: "/images"

locale: 'zh_Hans'

collections:
  - name: "posts"
    label: "文章"
    folder: "content/zh/posts"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "特色图片", name: "featured_image", widget: "image", required: false}
      - {label: "描述", name: "description", widget: "text"}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "pages"
    label: "页面"
    files:
      - file: "content/zh/_index.md"
        label: "首页"
        name: "home"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "描述", name: "description", widget: "text"}
          - {label: "内容", name: "body", widget: "markdown"}
      
      - file: "content/zh/about.md"
        label: "关于"
        name: "about"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "描述", name: "description", widget: "text"}
          - {label: "内容", name: "body", widget: "markdown"}
